{{- if ne .Values.create false -}}
{{- include "cv.utils.validateVersionAndRelease" . }}
{{- $objectname := include "cv.metadataname" . }}
{{- $statefulset := or .Values.statefulset .Values.global.statefulset }}

apiVersion: apps/v1 
kind: {{ if $statefulset }}StatefulSet{{ else }}Deployment{{ end }}
metadata:
  name: {{ $objectname }}
  namespace: {{ include "cv.namespace" . }}
  {{- include "cv.deploymentannotations" . }}
  labels:
    app.kubernetes.io/name: {{ $objectname }}
spec:
  {{- include "cv.commondeploymentspecs" . }}
  template:
    metadata:
      name: {{ $objectname }}
      labels:
        app.kubernetes.io/name: {{ $objectname }}
    spec:
      {{- include "cv.imagePullSecret" . }}
      {{- include "cv.additionalPodspecs" . }}
      containers:
      # Commserve
      - name: {{ $objectname }}
        image: {{ include "cv.image" . }}
        {{- include "cv.resources" . }}
        envFrom:
        - secretRef:
           name: {{ include "cv.metadataname2" (list . "cvcreds") }}
        env:
        {{- include "cv.commonenv" . }}
        {{- if .Values.email }}
        - name: CVID_EMAIL
          # Optional. Email of admin user
          value: {{ .Values.email }}
        {{- end }}
        # Ports can be left as mentioned as commserver needs all of them for correct functioning.   
        ports:
        - containerPort: 5000        
        - containerPort: 80
        - containerPort: {{ include "cv.cvfwdport" . }}
        - containerPort: 8400
        - containerPort: 8401
        - containerPort: 1433
        - containerPort: 27017
        - containerPort: 8052        
        volumeMounts:
        # This section contains list of persistent volumes that has to be mounted onto the container.                 
        # This can be left with default settings as mentioned in this template.
        {{- include "cv.commonVolumeMounts" . }}
        - name: cv-storage-csdb
          mountPath: /opt/commvaultDB
          subPath: commvaultDB
        - name: cv-storage-drbackups
          mountPath: /opt/commvaultDR
          subPath: drbackups
        - name: cv-storage-csdb
          mountPath: /var/opt/mssql
          subPath: mssql
        - name: cv-storage-cvmedia
          mountPath: /opt/commvault/SW/
          subPath: cvmedia
        {{- include "cv.additionalVolumeMounts" . }}
        {{ include "cv.commonContainerSpecs" . }}

      volumes:
      - name: podinfo
        downwardAPI:
          items:
            - path: "labels"
              fieldRef:
                fieldPath: metadata.labels
            - path: "annotations"
              fieldRef:
                fieldPath: metadata.annotations
      {{- if not $statefulset }}
      - name: cv-storage-certsandlogs
        persistentVolumeClaim:
           claimName: {{ $objectname }}-certsandlogs
      - name: cv-storage-csdb
        persistentVolumeClaim:
           claimName: {{ $objectname }}-csdb
      - name: cv-storage-drbackups
        persistentVolumeClaim:
           claimName: {{ $objectname }}-drbackups
      - name: cv-storage-cvmedia
        persistentVolumeClaim:
           claimName: {{ $objectname }}-cvmedia
      {{- include "cv.deployment.additionalVolumes" . }}
      {{- end }}

  {{- if $statefulset }}
  volumeClaimTemplates:
  {{- include "cv.statefulset.pvctemplate" (list . "certsandlogs" "50Gi") }}
  {{- include "cv.statefulset.pvctemplate" (list . "csdb" "100Gi") }}
  {{- include "cv.statefulset.pvctemplate" (list . "drbackups" "50Gi") }}
  {{- include "cv.statefulset.pvctemplate" (list . "cvmedia" "100Gi") }}
  {{- include "cv.statefulset.additionalPvcTemplates" . }}
  persistentVolumeClaimRetentionPolicy:
    whenScaled: {{ or .Values.whenScaled .Values.global.whenScaled | default "Delete" }}
    whenDeleted: {{ or .Values.whenDeleted .Values.global.whenDeleted | default "Delete" }}
  {{- end }}
{{- end }}
