{{- $objectname := include "cv.metadataname" . }}
{{- $statefulset := or .Values.statefulset .Values.global.statefulset }}

apiVersion: apps/v1 
kind: {{ if $statefulset }}StatefulSet{{ else }}Deployment{{ end }}
metadata:
  name: {{ $objectname }}
  namespace: {{(.Values.global).namespace}}
  {{- include "cv.deploymentannotations" . }}
  labels:
    app.kubernetes.io/name: {{ $objectname }}
spec:
  {{- include "cv.commondeploymentspecs" . }}
  template:
    metadata:
      name: {{ $objectname }}
      labels:
        app.kubernetes.io/name: {{ $objectname }}
    spec:
      {{- include "cv.imagePullSecret" . }}
      {{- include "cv.additionalPodspecs" . }}
      containers:
      # Commserve
      - name: {{ $objectname }}
        image: {{ include "cv.image" . }}
        {{- include "cv.resources" . }}
        envFrom:
        - secretRef:
           name: {{(.Values.global).appname}}cvcreds
        env:
        {{- include "cv.commonenv" . }}
        {{- if .Values.email }}
        - name: CVID_EMAIL
          # Optional. Email of admin user
          value: {{ .Values.email }}
        {{- end }}
        # Ports can be left as mentioned as commserver needs all of them for correct functioning.   
        ports:
        - containerPort: 5000        
        - containerPort: 80
        - containerPort: 8403
        - containerPort: 8400
        - containerPort: 8401
        - containerPort: 1433
        - containerPort: 27017
        - containerPort: 8052        
        volumeMounts:
        # This section contains list of persistent volumes that has to be mounted onto the container.                 
        # This can be left with default settings as mentioned in this template.
        - name: cv-storage-logs
          mountPath: /var/log/commvault/Log_Files
          subPath: Log_Files
        - name: cv-storage-certificates
          mountPath: /etc/CommVaultRegistry
          subPath: Registry   
        - name: cv-storage-certificates
          mountPath: /opt/commvault/appdata
          subPath: certificates
        - name: cv-storage-database
          mountPath: /opt/commvaultDB
          subPath: commvaultDB
        - name: cv-storage-drbackups
          mountPath: /opt/commvaultDR
          subPath: drbackups
        - name: cv-storage-database
          mountPath: /var/opt/mssql
          subPath: mssql

      {{- if not $statefulset }}          
      volumes:
      - name: cv-storage-logs
        persistentVolumeClaim:
           claimName: {{ $objectname }}-logs
      - name: cv-storage-certificates
        persistentVolumeClaim:
           claimName: {{ $objectname }}-certificates
      - name: cv-storage-database
        persistentVolumeClaim:
           claimName: {{ $objectname }}-database
      - name: cv-storage-drbackups
        persistentVolumeClaim:
           claimName: {{ $objectname }}-drbackups
      {{- end }}

  {{- if $statefulset }}
  volumeClaimTemplates:
  {{- include "cv.pvctemplate" (list . "logs" "50Gi") }}
  {{- include "cv.pvctemplate" (list . "certificates" "25M") }}
  {{- include "cv.pvctemplate" (list . "database" "100Gi") }}
  {{- include "cv.pvctemplate" (list . "drbackups" "50Gi") }}
  persistentVolumeClaimRetentionPolicy:
    whenScaled: {{ or .Values.whenScaled .Values.global.whenScaled | default "Delete" }}
    whenDeleted: {{ or .Values.whenDeleted .Values.global.whenDeleted | default "Delete" }}
  {{- end }}
