{{- if ne .Values.create false -}}
{{ $statefulset := or .Values.statefulset .Values.global.statefulset }}
{{- if not $statefulset }}

{{ include "cv.deployment.pvc" (list . "certsandlogs" "50Gi") }}

{{ include "cv.deployment.pvc" (list . "csdb" "100Gi") }}

{{ include "cv.deployment.pvc" (list . "drbackups" "50Gi") }}

{{ include "cv.deployment.pvc" (list . "cvmedia" "100Gi") }}

{{ include "cv.deployment.additionalPvc" . }}

{{ end }}
{{- end }}
