# Required. client display name
clientName: 

# Optional. hostname of the client should match the service fqdn.
clientHostName: 

# final image value wil be registry/namespace/repository:tag
image: 
  # Optional. Overrides gobal value. Must end with /
  registry: 
  # Optional image namespace or account. Overrides gobal value. Default is commvault
  namespace: 
  # Optional. Default value is mediaagent
  repository: 
  # Required unless global.image.tag is specified. Overrides gobal value.
  tag: 

storageClass:
  # Optional. Name of the storage class for job results. Default storage class will be used if not specified. Overrides global values
  jobresults: 
  # Optional. default is "20Gi". Overrides global values
  jobresults_size: 
  # Optional. Name of the storage class for index cache. Default storage class will be used if not specified. Overrides global values
  indexcache: 
  # Optional. default is "20Gi". Overrides global values
  indexcache_size: 
  # Optional. Name of the storage class for ddb. Default storage class will be used if not specified. Overrides global values
  ddb: 
  # Optional. default is "50Gi". Overrides global values
  ddb_size: 

# Optional. Will be merged with global annotations and also override matching global annotations
deploymentannotations: 

# Optional. Will be merged with global annotations and also override matching global annotations
serviceannotations:

# Optional. Use this to add additional values to the pod specifications such as nodeSelector. These will merge and override any global additionalPodspecs
additionalPodspecs:

# Optional. Deployment requests and limits. Enable only those values that need to be set. This also overrides any global values
# resources:
#   requests:
#     memory: 
#     cpu:
#   limits:
#     memory:
#     cpu: 
