# Required. client display name
clientName: 

# Optional. hostname of the client should match the service fqdn.
clientHostName: 

# final image value wil be registry/namespace/repository:tag
image: 
  # Optional. Overrides gobal value. Must end with /
  registry: 
  # Optional image namespace or account. Overrides gobal value. Default is commvault
  namespace: 
  # Optional. Default value is networkgateway
  repository: 
  # Required unless global.image.tag is specified. Overrides gobal value.
  tag: 

# Optional. Will be merged with global annotations and also override matching global annotations
deploymentannotations: 

# Optional. Will be merged with global annotations and also override matching global annotations
serviceannotations:

# Optional. Use this to add additional values to the pod specifications such as nodeSelector. These will merge and override any global additionalPodspecs
#Example:
#additionalPodspecs:
#  nodeSelector: 
#    disktype: ssd

# Optional. Deployment requests and limits. Enable only those values that need to be set. This also overrides any global values
#resources:
#  requests:
#    memory: 
#    cpu:
#  limits:
#    memory:
#    cpu: 

# Optional. Additional volumes can be mounted in the pod. These volumes will be in addition to any volumes from global values
# Both storageClass and volume are optional fields. volume takes precedence over storageClass for Deployment
# volumes:
#   - name: vol1
#     mountPath: /var/opt/vol1
#     subPath: vol1
#     size: 1Gi
#     storageClass: default
#     volume: vVol1
