{{- include "cv.utils.validateVersionAndRelease" . }}
{{- $objectname := include "cv.metadataname" . }}
{{- $statefulset := or .Values.statefulset .Values.global.statefulset }}

apiVersion: apps/v1 
kind: {{ if $statefulset }}StatefulSet{{ else }}Deployment{{ end }}
metadata:
  name: {{ $objectname }}
  namespace: {{(.Values.global).namespace}}
  {{- include "cv.deploymentannotations" . }}
  labels:
    app.kubernetes.io/name: {{ $objectname }}
spec:
  {{- include "cv.commondeploymentspecs" . }}
  template:
    metadata:
      name: {{ $objectname }}
      labels:
        app.kubernetes.io/name: {{ $objectname }}
    spec:
      {{- include "cv.imagePullSecret" . }}
      {{- include "cv.additionalPodspecs" . }}
      containers:
      # Command center
      - name: {{ $objectname }} 
        image: {{ include "cv.image" . }}
        {{- include "cv.resources" . }}
        envFrom:
        - configMapRef:
           name: {{(.Values.global).appname}}cvconfig
        - secretRef:
           name: {{(.Values.global).appname}}cvcreds
        env:              
        {{- include "cv.commonenv" . }}
        - name: CV_WS_CLIENT_NAME 
          # The clientName of the webserver the command center needs to be connected to
          value: {{if .Values.webserverName}}{{tpl .Values.webserverName .}}{{end}}
        # ports can be left default
        ports:
        - containerPort: 8403
        - containerPort: {{ .Values.httpPort | default 80 }}
        - containerPort: {{ .Values.httpsPort | default 443 }}
        volumeMounts:
        # This section contains list of persistent volumes that has to be mounted onto the container.                 
        # This can be left with default settings as mentioned in this template.
        {{- include "cv.commonVolumeMounts" . }}
        {{- include "cv.additionalVolumeMounts" . }}
        {{ include "cv.commonContainerSpecs" . }}

      volumes:
      - name: podinfo
        downwardAPI:
          items:
            - path: "labels"
              fieldRef:
                fieldPath: metadata.labels
            - path: "annotations"
              fieldRef:
                fieldPath: metadata.annotations
      {{- if not $statefulset }}
      - name: cv-storage-certsandlogs
        persistentVolumeClaim:
           claimName: {{ $objectname }}-certsandlogs
      {{- include "cv.deployment.additionalVolumes" . }}
      {{- end }}

  {{- if $statefulset }}
  volumeClaimTemplates:
  {{- include "cv.statefulset.pvctemplate" (list . "certsandlogs" "10Gi") }}
  {{- include "cv.statefulset.additionalPvcTemplates" . }}
  persistentVolumeClaimRetentionPolicy:
    whenScaled: {{ or .Values.whenScaled .Values.global.whenScaled | default "Delete" }}
    whenDeleted: {{ or .Values.whenDeleted .Values.global.whenDeleted | default "Delete" }}
  {{- end }}
