{{ $objectname := include "cv.metadataname" . }}
{{ $statefulset := or .Values.statefulset .Values.global.statefulset }}

apiVersion: apps/v1 
kind: {{ if $statefulset }}StatefulSet{{ else }}Deployment{{ end }}
metadata:
  name: {{ $objectname }}
  namespace: {{(.Values.global).namespace}}
  {{- include "cv.deploymentannotations" . }}
  labels:
    app.kubernetes.io/name: {{ $objectname }}
spec:
  {{- if $statefulset }}
  serviceName: {{ .Values.serviceName | default $objectname }}
  replicas: {{ .Values.replicas | default 1 }}
  updateStrategy:
    type: RollingUpdate
  {{- else }}
  replicas: 1  
  strategy:
    type: Recreate
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $objectname }}    
  template:
    metadata:
      name: {{ $objectname }}
      labels:
        app.kubernetes.io/name: {{ $objectname }}
    spec:
      {{- include "cv.imagePullSecret" . }}
      {{- include "cv.additionalPodspecs" . }}
      containers:
      # Mediaagent
      - name: {{ $objectname }}
        image: {{ include "cv.image" . }}
        {{- include "cv.resources" . }}
        envFrom:
        - configMapRef:
           name: {{(.Values.global).appname}}cvconfig
        - secretRef:
           name: {{(.Values.global).appname}}cvcreds
        env:
        {{- include "cv.commonenv" . }}
        # ports can be left default
        ports:                                                      
        - containerPort: 8403    
        volumeMounts:
        # This section contains list of persistent volumes that has to be mounted onto the container.                 
        # This can be left with default settings as mentioned in this template.
        - name: cv-storage-logs
          mountPath: /var/log/commvault/Log_Files
          subPath: Log_Files
        - name: cv-storage-certificates
          mountPath: /etc/CommVaultRegistry
          subPath: Registry   
        - name: cv-storage-certificates
          mountPath: /opt/commvault/appdata
          subPath: certificates
        - name: cv-storage-jobresults
          mountPath: /opt/commvault/iDataAgent/jobResults
          subPath: jobResults
        - name: cv-storage-indexcache
          mountPath: /opt/commvault/MediaAgent/IndexCache
          subPath: indexcache
        - name: cv-storage-ddb
          mountPath: /opt/ddb
          subPath: ddb

      {{- if not $statefulset }}
      volumes:
      - name: cv-storage-logs
        persistentVolumeClaim:
           claimName: {{ $objectname }}-logs
      - name: cv-storage-certificates
        persistentVolumeClaim:
           claimName: {{ $objectname }}-certificates
      - name: cv-storage-jobresults
        persistentVolumeClaim:
           claimName: {{ $objectname }}-jobresults
      - name: cv-storage-indexcache
        persistentVolumeClaim:
           claimName: {{ $objectname }}-indexcache
      - name: cv-storage-ddb
        persistentVolumeClaim:
           claimName: {{ $objectname }}-ddb
      {{- end }}

  {{- if $statefulset }}
  volumeClaimTemplates:
  {{- include "cv.pvctemplate" (list . "logs" "10Gi") }}
  {{- include "cv.pvctemplate" (list . "certificates" "25M") }}
  {{- include "cv.pvctemplate" (list . "jobresults" "20Gi") }}
  {{- include "cv.pvctemplate" (list . "indexcache" "20Gi") }}
  {{- include "cv.pvctemplate" (list . "ddb" "50Gi") }}
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Delete
    whenScaled: Delete
  {{- end }}

