{{- if ne .Values.create false -}}
{{- include "cv.utils.validateVersionAndRelease" . }}
{{- $objectname := include "cv.metadataname" . }}
{{- $statefulset := or .Values.statefulset ((.Values).global).statefulset }}

apiVersion: apps/v1 
kind: {{ if $statefulset }}StatefulSet{{ else }}Deployment{{ end }}
metadata:
  name: {{ $objectname }}
  namespace: {{ include "cv.namespace" . }}
  {{- include "cv.deploymentannotations" . }}
  labels:
    app.kubernetes.io/name: {{ $objectname }}
spec:
  {{- include "cv.commondeploymentspecs" . }}
  template:
    metadata:
      name: {{ $objectname }}
      labels:
        app.kubernetes.io/name: {{ $objectname }}
    spec:
      {{- include "cv.imagePullSecret" . }}
      {{- include "cv.additionalPodspecs" . }}
      containers:
      # Mediaagent
      - name: {{ $objectname }}
        image: {{ include "cv.image" . }}
        {{- include "cv.resources" . }}
        envFrom:
        - configMapRef:
           name: {{ include "cv.metadataname2" (list . "cvconfig") }}
           optional: true
        - secretRef:
           name: {{ include "cv.metadataname2" (list . "cvcreds") }}
           optional: true
        env:
        {{- include "cv.commonenv" . }}
        # ports can be left default
        ports:                                                      
        - containerPort: {{ include "cv.cvfwdport" . }}
        - containerPort: 8400
        volumeMounts:
        # This section contains list of persistent volumes that has to be mounted onto the container.                 
        # This can be left with default settings as mentioned in this template.
        {{- include "cv.commonVolumeMounts" . }}
        - name: cv-storage-jobresults
          mountPath: /opt/commvault/iDataAgent/jobResults
          subPath: jobResults
        - name: cv-storage-indexcache
          mountPath: /opt/commvault/MediaAgent/IndexCache
          subPath: indexcache
        - name: cv-storage-ddb
          mountPath: /opt/ddb
          subPath: ddb
        {{- include "cv.additionalVolumeMounts" . }}
        {{ include "cv.commonContainerSpecs" . }}

      volumes:
      - name: podinfo
        downwardAPI:
          items:
            - path: "labels"
              fieldRef:
                fieldPath: metadata.labels
            - path: "annotations"
              fieldRef:
                fieldPath: metadata.annotations
      {{- if not $statefulset }}
      - name: cv-storage-certsandlogs
        persistentVolumeClaim:
           claimName: {{ $objectname }}-certsandlogs
      - name: cv-storage-jobresults
        persistentVolumeClaim:
           claimName: {{ $objectname }}-jobresults
      - name: cv-storage-indexcache
        persistentVolumeClaim:
           claimName: {{ $objectname }}-indexcache
      - name: cv-storage-ddb
        persistentVolumeClaim:
           claimName: {{ $objectname }}-ddb
      {{- include "cv.deployment.additionalVolumes" . }}
      {{- end }}

  {{- if $statefulset }}
  volumeClaimTemplates:
  {{- include "cv.statefulset.pvctemplate" (list . "certsandlogs" "10Gi") }}
  {{- include "cv.statefulset.pvctemplate" (list . "jobresults" "20Gi") }}
  {{- include "cv.statefulset.pvctemplate" (list . "indexcache" "20Gi") }}
  {{- include "cv.statefulset.pvctemplate" (list . "ddb" "50Gi") }}
  {{- include "cv.statefulset.additionalPvcTemplates" . }}
  persistentVolumeClaimRetentionPolicy:
    whenScaled: {{ or .Values.whenScaled .Values.global.whenScaled | default "Delete" }}
    whenDeleted: {{ or .Values.whenDeleted .Values.global.whenDeleted | default "Delete" }}
  {{- end }}
{{- end }}
