{{ $statefulset := or .Values.statefulset .Values.global.statefulset }}
{{- if not $statefulset }}
{{ include "cv.deployment.pvc" (list . "certsandlogs" "10Gi") }}

{{ include "cv.deployment.pvc" (list . "jobresults" "20Gi") }}

{{ include "cv.deployment.pvc" (list . "indexcache" "20Gi") }}

{{ include "cv.deployment.pvc" (list . "ddb" "50Gi") }}

{{ include "cv.deployment.additionalPvc" . }}

{{ end }}
