# PVC for log files.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "cv.metadataname" . }}-logs
  namespace: {{(.Values.global).namespace}}
spec:
  accessModes:
    - ReadWriteOnce
  # leave this if condition alone. otherwise it can cause problem on restart if storageclassname is blank
  {{- if or (.Values.storageClass).logs ((.Values.global).storageClass).logs }}
  storageClassName: {{ or (.Values.storageClass).logs ((.Values.global).storageClass).logs }}
  {{- end}}
  resources:
    requests:
      storage: {{ or (.Values.storageClass).logs_size ((.Values.global).storageClass).logs_size "10Gi" }}

---

# PVC for registry and certificates.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "cv.metadataname" . }}-certificates
  namespace: {{(.Values.global).namespace}}
spec:
  accessModes:
    - ReadWriteOnce
  # leave this if condition alone. otherwise it can cause problem on restart if storageclassname is blank
  {{- if or (.Values.storageClass).certificates ((.Values.global).storageClass).certificates }}
  storageClassName: {{ or (.Values.storageClass).certificates ((.Values.global).storageClass).certificates }}
  {{- end}}
  resources:
    requests:
      storage: {{ or (.Values.storageClass).certificates_size ((.Values.global).storageClass).certificates_size "25M" }}

---

# PVC for job results
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "cv.metadataname" . }}-jobresults
  namespace: {{(.Values.global).namespace}}
spec:
  accessModes:
    - ReadWriteOnce
  # leave this if condition alone. otherwise it can cause problem on restart if storageclassname is blank
  {{- if or (.Values.storageClass).jobresults ((.Values.global).storageClass).jobresults }}
  storageClassName: {{ or (.Values.storageClass).jobresults ((.Values.global).storageClass).jobresults }}
  {{- end}}
  resources:
    requests:
      storage: {{ or (.Values.storageClass).jobresults_size ((.Values.global).storageClass).jobresults_size "20Gi" }}

---

# PVC for index cache
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "cv.metadataname" . }}-indexcache
  namespace: {{(.Values.global).namespace}}
spec:
  accessModes:
    - ReadWriteOnce
  # leave this if condition alone. otherwise it can cause problem on restart if storageclassname is blank
  {{- if or (.Values.storageClass).indexcache ((.Values.global).storageClass).indexcache }}
  storageClassName: {{ or (.Values.storageClass).indexcache ((.Values.global).storageClass).indexcache }}
  {{- end}}
  resources:
    requests:
      storage: {{ or (.Values.storageClass).indexcache_size ((.Values.global).storageClass).indexcache_size "20Gi" }}

---

# PVC for ddb
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "cv.metadataname" . }}-ddb
  namespace: {{(.Values.global).namespace}}
spec:
  accessModes:
    - ReadWriteOnce
  # leave this if condition alone. otherwise it can cause problem on restart if storageclassname is blank
  {{- if or (.Values.storageClass).ddb ((.Values.global).storageClass).ddb }}
  storageClassName: {{ or (.Values.storageClass).ddb ((.Values.global).storageClass).ddb }}
  {{- end}}
  resources:
    requests:
      storage: {{ or (.Values.storageClass).ddb_size ((.Values.global).storageClass).ddb_size "50Gi" }}

