{{ $statefulset := or .Values.statefulset .Values.global.statefulset }}
{{- if not $statefulset }}
{{ include "cv.pvc" (list . "logs" "10Gi") }}

---

{{ include "cv.pvc" (list . "certificates" "25M") }}

---

{{ include "cv.pvc" (list . "jobresults" "20Gi") }}

---

{{ include "cv.pvc" (list . "indexcache" "20Gi") }}

---

{{ include "cv.pvc" (list . "ddb" "50Gi") }}
{{ end }}
