apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cv.metadataname2" (list . "cvconfig") }}
  namespace: {{ include "cv.namespace" . }}
data:  
  # host name of the Commserve or gateway
  CV_CSHOSTNAME: {{ tpl .Values.csOrGatewayHostName . }}
  {{- if .Values.csClientName }}
  CV_CSCLIENTNAME: {{ tpl .Values.csClientName . }}
  {{- end }}
