{{- $cvpatcher := true  }}
{{- if hasKey .Values "cvpatcher" }}
{{- $cvpatcher = .Values.cvpatcher }}
{{- end }}
{{- if $cvpatcher }}
{{- $objectname := include "cv.metadataname2" (list . "cvpatcher") }}
apiVersion: v1 
kind: Service 
metadata:
  name: {{ $objectname }}
  namespace: {{ include "cv.namespace" . }}
spec:      
  type: ClusterIP
  ports:
    - name: cvpatcher
      port: 6688
      targetPort: 6688      
      protocol: TCP 
  selector:
    app.kubernetes.io/name: {{ $objectname }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $objectname }}
  namespace: {{ include "cv.namespace" . }}
  labels:
    app.kubernetes.io/name: {{ $objectname }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $objectname }}
  template:
    metadata:
      name: {{ $objectname }}
      labels:
        app.kubernetes.io/name: {{ $objectname }}
    spec:
      {{- include "cv.imagePullSecret" . }}
      containers:
      - name: cvpatcher
        image: {{ include "cv.cvpatcherimage" . }}
        imagePullPolicy: Always
        env:
        {{- if (.Values.global).prefix }}
        - name: CV_APP_PREFIX
          value: "{{ tpl (.Values.global).prefix . }}"
        {{- end }}
        {{- if (.Values.global).suffix }}
        - name: CV_APP_SUFFIX
          value: "{{ tpl (.Values.global).suffix . }}"
        {{- end }}
        {{- include "cv.resources" . }}
        ports:
        - containerPort: 6688

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ $objectname }}-ns-restriction
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ $objectname }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector: {}
          namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ include "cv.namespace" . }}
{{ end }}
