{{ if (.Values.namespace) }}
{{ if ne .Values.namespace.create false }}
{{ if (.Values.global).namespace }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ (.Values.global).namespace }}
---
# Default deny all ingress traffic to the namespace
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-ingress
  namespace: {{ (.Values.global).namespace }}
spec:
  podSelector: {}
  policyTypes:
  - Ingress
{{ end }}
{{ end }}
{{ end }}
