{{ if (.Values.namespace) }}
{{ if ne .Values.namespace.create false }}
{{ if (.Values.global).namespace }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ (.Values.global).namespace }}
{{ end }}
{{ end }}
{{ end }}
