{{- $createViewRole := true  }}
{{- if hasKey .Values "createViewRole" }}
{{- $createViewRole = .Values.createViewRole }}
{{- end }}
{{- if $createViewRole }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "cv.metadataname2" (list . "cv-view") }}
  namespace: {{ include "cv.namespace" . }}
rules:
{{/*
"" indicates the core API group
*/}}
- apiGroups: [""]
  resources: ["pods","secrets"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["apps"]
  resources: ["statefulsets", "deployments","replicasets"]
  verbs: ["get", "watch", "list"]
{{ end }}
