{{- $createViewRole := true  }}
{{- if hasKey .Values "createViewRole" }}
{{- $createViewRole = .Values.createViewRole }}
{{- end }}
{{- if $createViewRole }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "cv.metadataname2" (list . "cv-view") }}
  namespace: {{ include "cv.namespace" . }}
  labels:
    app.kubernetes.io/name: {{ include "cv.metadataname2" (list . "cv-view") }}
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ include "cv.namespace" . }}
roleRef:
  kind: Role
  name: {{ include "cv.metadataname2" (list . "cv-view") }}
  apiGroup: rbac.authorization.k8s.io
{{ end }}

---

{{- $cvpatcher := true  }}
{{- if hasKey .Values "cvpatcher" }}
{{- $cvpatcher = .Values.cvpatcher }}
{{- end }}
{{- if $cvpatcher }}
{{- $serviceAccount := .Values.serviceAccount | default dict }}
{{- $rbac := .Values.rbac | default dict }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "cv.metadataname2" (list . "cvpatcher") }}
  namespace: {{ include "cv.namespace" . }}
  labels:
    app.kubernetes.io/name: {{ include "cv.metadataname2" (list . "cvpatcher") }}
subjects:
- kind: ServiceAccount
  name: {{ $serviceAccount.name | default (include "cv.metadataname2" (list . "cvpatcher")) }}
  namespace: {{ include "cv.namespace" . }}
roleRef:
  kind: Role
  name: {{ $rbac.roleName | default (include "cv.metadataname2" (list . "cvpatcher")) }}
  apiGroup: rbac.authorization.k8s.io
{{ end }}

