{{- $createViewRole := true  }}
{{- if hasKey .Values "createViewRole" }}
{{- $createViewRole = .Values.createViewRole }}
{{- end }}
{{- if $createViewRole }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ (.Values.global).appname}}cv-view
  namespace: {{ (.Values.global).namespace }}
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ or (.Values.global).namespace "default" }}
roleRef:
  kind: Role
  name: {{ (.Values.global).appname}}cv-view
  apiGroup: ""
{{ end }}
