apiVersion: v1
kind: Secret
metadata:  
  name: {{(.Values.global).appname}}cvcreds
  namespace: {{(.Values.global).namespace}}
data:
  # This section contains the credentials to connect to the Commserver. 
  # User names and password should be base-64 encoded.
  CV_COMMCELL_USER: {{ or (.Values.secret).user "" | b64enc }}
  CV_COMMCELL_PWD: {{ or (.Values.secret).password "" | b64enc }}

---

{{if and .Values.imageCredentials (.Values.imageCredentials).registry}}
apiVersion: v1
kind: Secret
metadata:  
  name: {{(.Values.global).appname}}{{((.Values.global).image).pullSecret}}
  namespace: {{(.Values.global).namespace}}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "cv.imagePullSecretCredentials" . }}
{{end}}
