apiVersion: v1
kind: Secret
metadata:  
  name: {{ include "cv.metadataname2" (list . "cvcreds") }}
  namespace: {{ include "cv.namespace" . }}
data:
  # This section contains the credentials to connect to the Commserver. 
  # User names and password should be base-64 encoded.
  CV_COMMCELL_USER: {{ or (.Values.secret).user "" | b64enc }}
  CV_COMMCELL_PWD: {{ or (.Values.secret).password "" | b64enc }}

---

{{if (.Values.pullsecret).create }}
apiVersion: v1
kind: Secret
metadata:  
  name: {{ include "cv.metadataname2" (list . .Values.pullsecret.name) }}
  namespace: {{ include "cv.namespace" . }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "cv.imagePullSecretCredentials" . }}
{{end}}
