# This creates a dedicated service account for the cvpatcher deployment BY DEFAULT
# instead of using the default service account which may have excessive permissions

{{- $cvpatcher := true  }}
{{- if hasKey .Values "cvpatcher" }}
{{- $cvpatcher = .Values.cvpatcher }}
{{- end }}
{{- if $cvpatcher }}
{{- $serviceAccount := .Values.serviceAccount | default dict }}
{{- $createSA := true }}
{{- if hasKey $serviceAccount "create" }}
{{- $createSA = $serviceAccount.create }}
{{- end }}
{{- if or (not $createSA) (eq (toString $createSA) "false") }}
{{- fail "\n\nSECURITY ERROR: CVPatcher requires dedicated service account for security.\n\nThe default service account has insufficient permissions for CVPatcher operations.\n\nTo fix this:\n1. Remove 'serviceAccount.create: false' from values.yaml, OR\n2. Set 'serviceAccount.create: true' explicitly, OR\n3. Disable CVPatcher with 'cvpatcher: false'\n\nUsing default service account would cause CVPatcher to fail due to missing permissions.\n" }}
{{- end }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $serviceAccount.name | default (include "cv.metadataname2" (list . "cvpatcher-sa")) }}
  namespace: {{ include "cv.namespace" . }}
  labels:
    app.kubernetes.io/name: {{ include "cv.metadataname2" (list . "cvpatcher") }}
# automountServiceAccountToken: true allows the pod to access Kubernetes API BY DEFAULT
automountServiceAccountToken: {{ $serviceAccount.automountServiceAccountToken | default true }}
{{ end }}


