{{- $createClusterViewRole := true  }}
{{- if hasKey .Values "createClusterViewRole" }}
{{- $createClusterViewRole = .Values.createClusterViewRole }} 
{{- end }}

{{- $crName := include "cv.metadataname2" (list . (.Values.CvDDBBackupCRName | default "cv-ddb-backup")) }}
{{- if $createClusterViewRole  }}
# DEBUG: crName = {{ $crName }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:                           
  name: {{ $crName }}
rules:
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses", "csidrivers", "VolumeSnapshotClass", "VolumeSnapshot", "VolumeSnapshotContent"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshotclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["persistentvolumes", "persistentvolumeclaims"]
    verbs: ["get", "list", "watch"]
{{- end }}
