{{- $createClusterViewRoleBinding := true  }}
{{- if hasKey .Values "createClusterViewRoleBinding" }}
{{- $createClusterViewRoleBinding = .Values.createClusterViewRoleBinding }}
{{- end }}

{{- if $createClusterViewRoleBinding }}
{{- $crName := include "cv.metadataname2" (list . (.Values.CvDDBBackupCRName | default "cv-ddb-backup")) }}
{{- $targetNamespaces := required "targetNamespaces is required and must be a non-empty list" .Values.targetNamespaces }}
{{- range $index, $namespace := $targetNamespaces }}
{{- if gt $index 0 }}
---
{{- end }}
{{- $crbName := printf "%s-%s" $namespace $crName }}
# DEBUG: crbName = {{ $crbName }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $crbName }}
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ $namespace }}
roleRef:
  kind: ClusterRole
  name: {{ $crName }}
  apiGroup: "rbac.authorization.k8s.io"
{{- end }}
{{- end }}