{{ $statefulset := or .Values.statefulset .Values.global.statefulset }}
{{- if not $statefulset }}
{{ include "cv.pvc" (list . "logs" "10Gi") }}

---

{{ include "cv.pvc" (list . "certificates" "25M") }}

---

{{ include "cv.pvc" (list . "cache" "10Gi") }}
{{ end }}
