apiVersion: v1 
kind: Service 
metadata:
  name: {{ include "cv.metadataname" . }}
  namespace: {{(.Values.global).namespace}}
  {{- include "cv.serviceannotations" . }}
  labels:
    app.kubernetes.io/name: {{(.Values.global).appname}}{{ tpl .Values.clientName . }}
spec:      
  type: {{ if .Values.serviceType }}{{ .Values.serviceType }}{{ else }}LoadBalancer{{ end }}
  ports:
    # This section contains the port numbers that are needed for correct functioning of the Webserver. 
    # This can be left with default settings as mentioned in this template. 
    - name: cvfwd
      port: 8403
      targetPort: 8403                        
      protocol: TCP 
    - name: webservice
      port: 5000
      targetPort: 5000
      protocol: TCP     
    - name: tomcat 
      port: 80
      targetPort: 80      
      protocol: TCP 
    - name: messagequeue
      port: 8052
      targetPort: 8052     
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "cv.metadataname" . }}
