{{- if ne .Values.create false -}}
{{ $statefulset := or .Values.statefulset ((.Values).global).statefulset }}
apiVersion: v1 
kind: Service 
metadata:
  name: {{ include "cv.metadataname" . }}
  namespace: {{ include "cv.namespace" . }}
  {{- include "cv.serviceannotations" . }}
  labels:
    app.kubernetes.io/name: {{(.Values.global).prefix}}{{ tpl .Values.clientName . }}
spec:      
  type: {{ if .Values.serviceType }}{{ .Values.serviceType }}{{ else }}ClusterIP{{ end }}
  ports:
    # This section contains the port numbers that are needed for correct functioning of the Webserver. 
    # This can be left with default settings as mentioned in this template. 
    - name: cvfwd
      port: {{ include "cv.cvfwdport" . }}
      targetPort: {{ include "cv.cvfwdport" . }}
      protocol: TCP 
    - name: webservice
      port: 5000
      targetPort: 5000
      protocol: TCP     
    - name: tomcat 
      port: 80
      targetPort: 80      
      protocol: TCP 
    - name: messagequeue
      port: 8052
      targetPort: 8052     
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "cv.metadataname" . }}
{{- end }}
