{{- include "cv.utils.validateVersionAndRelease" . }}
{{- $objectname := include "cv.metadataname" . }}
{{- $statefulset := or .Values.statefulset .Values.global.statefulset }}

apiVersion: apps/v1 
kind: {{ if $statefulset }}StatefulSet{{ else }}Deployment{{ end }}
metadata:
  name: {{ $objectname }}
  namespace: {{(.Values.global).namespace}}
  {{- include "cv.deploymentannotations" . }}
  labels:
    app.kubernetes.io/name: {{ $objectname }}
spec:
  {{- include "cv.commondeploymentspecs" . }}
  template:
    metadata:
      name: {{ $objectname }}
      labels:
        app.kubernetes.io/name: {{ $objectname }}
    spec:
      {{- include "cv.imagePullSecret" . }}
      {{- include "cv.additionalPodspecs" . }}
      containers:
      # access node
      - name: {{ $objectname }}
        image: {{ include "cv.image" . }}
        {{- include "cv.resources" . }}
        envFrom:
        - configMapRef:
           name: {{(.Values.global).appname}}cvconfig
        - secretRef:
           name: {{(.Values.global).appname}}cvcreds
        env:
        {{- include "cv.commonenv" . }}
        # ports can be left default
        ports:                                                      
        - containerPort: 8403    
        volumeMounts:
        # This section contains list of persistent volumes that has to be mounted onto the container.                 
        # This can be left with default settings as mentioned in this template.
        - name: podinfo
          mountPath: /etc/podinfo        
        - name: cv-storage-logs
          mountPath: /var/log/commvault/Log_Files
          subPath: Log_Files
        - name: cv-storage-certificates
          mountPath: /etc/CommVaultRegistry
          subPath: Registry   
        - name: cv-storage-certificates
          mountPath: /opt/commvault/appdata
          subPath: certificates
        - name: cv-storage-jobresults
          mountPath: /opt/commvault/iDataAgent/jobResults
          subPath: jobResults
        {{- include "cv.additionalVolumeMounts" . }}
          
      volumes:
      - name: podinfo
        downwardAPI:
          items:
            - path: "labels"
              fieldRef:
                fieldPath: metadata.labels
            - path: "annotations"
              fieldRef:
                fieldPath: metadata.annotations
      {{- if not $statefulset }}
      - name: cv-storage-logs
        persistentVolumeClaim:
           claimName: {{ $objectname }}-logs
      - name: cv-storage-certificates
        persistentVolumeClaim:
           claimName: {{ $objectname }}-certificates
      - name: cv-storage-jobresults
        persistentVolumeClaim:
           claimName: {{ $objectname }}-jobresults
      {{- include "cv.deployment.additionalVolumes" . }}
      {{- end }}

  {{- if $statefulset }}
  volumeClaimTemplates:
  {{- include "cv.statefulset.pvctemplate" (list . "logs" "10Gi") }}
  {{- include "cv.statefulset.pvctemplate" (list . "certificates" "25M") }}
  {{- include "cv.statefulset.pvctemplate" (list . "jobresults" "20Gi") }}
  {{- include "cv.statefulset.additionalPvcTemplates" . }}
  persistentVolumeClaimRetentionPolicy:
    whenScaled: {{ or .Values.whenScaled .Values.global.whenScaled | default "Delete" }}
    whenDeleted: {{ or .Values.whenDeleted .Values.global.whenDeleted | default "Delete" }}
  {{- end }}
