{{- if ne .Values.create false -}}
{{ $statefulset := or .Values.statefulset ((.Values).global).statefulset }}
{{- $blockCrossNamespace := or .Values.blockCrossNamespace ((.Values.global).blockCrossNamespace) }}
apiVersion: v1 
kind: Service 
metadata:
  name: {{ include "cv.metadataname" . }}
  namespace: {{ include "cv.namespace" . }}
  {{- include "cv.serviceannotations" . }}
  labels:
    app.kubernetes.io/name: {{ include "cv.metadataname" . }}
spec:      
  type: {{ if .Values.serviceType }}{{ .Values.serviceType }}{{ else if $statefulset }}ClusterIP{{ else }}ClusterIP{{ end }}
  ports:
    - name: cvfwd
      port: {{ include "cv.cvfwdport" . }}
      targetPort: {{ include "cv.cvfwdport" . }}
      protocol: TCP 
    {{- if or .Values.indexgatewayport (.Values.global).indexgatewayport }}
    - name: indexgateway
      port: {{ include "cv.indexgatewayport" . }}
      targetPort: {{ include "cv.indexgatewayport" . }}
      protocol: TCP
    {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "cv.metadataname" . }}

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "cv.metadataname" . }}-access-restriction
  namespace: {{ include "cv.namespace" . }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "cv.metadataname" . }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        {{- if $blockCrossNamespace }}
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ include "cv.namespace" . }}
        {{- else }}
        - namespaceSelector: {}
        {{- end }}
      ports:
        - port: {{ include "cv.cvfwdport" . }} 
          protocol: TCP
        {{- if or .Values.indexgatewayport (.Values.global).indexgatewayport }}
        - port: {{ include "cv.indexgatewayport" . }}
          protocol: TCP
        {{- end }}
{{ end }}
