{{ $statefulset := or .Values.statefulset .Values.global.statefulset }}
apiVersion: v1 
kind: Service 
metadata:
  name: {{ include "cv.metadataname" . }}
  namespace: {{(.Values.global).namespace}}
  {{- include "cv.serviceannotations" . }}
  labels:
    app.kubernetes.io/name: {{ include "cv.metadataname" . }}
spec:      
  type: {{ if .Values.serviceType }}{{ .Values.serviceType }}{{ else if $statefulset }}ClusterIP{{ else }}ClusterIP{{ end }}
  ports:
    - name: cvfwd
      port: 8403
      targetPort: 8403                        
      protocol: TCP 
  selector:
    app.kubernetes.io/name: {{ include "cv.metadataname" . }}

